const BattleshipGame = (() => {
  const SIZE = 10;
  const fleet = [{ name: 'Carrier', size: 5 }, { name: 'Battleship', size: 4 }, { name: 'Cruiser', size: 3 }, { name: 'Submarine', size: 3 }, { name: 'Destroyer', size: 2 }];
  let boards, ships, mode, phase, setupPlayer, turn, selectedShip, horizontal, computerTimer, computerTargets;
  const makeBoard = () => Array.from({ length: SIZE }, () => Array.from({ length: SIZE }, () => ({ ship: null, shot: false })));
  const inside = (r, c) => r >= 0 && r < SIZE && c >= 0 && c < SIZE;
  function newGame() { clearTimeout(computerTimer); mode = document.getElementById('mode-select').value; boards = [makeBoard(), makeBoard()]; ships = [makeShips(), makeShips()]; phase = 'setup'; setupPlayer = 0; turn = 0; selectedShip = 0; horizontal = true; computerTargets = []; if (mode === 'computer') randomFleet(1); render(); status('Player 1: place your fleet.'); }
  function makeShips() { return fleet.map(ship => ({ ...ship, cells: [], sunk: false })); }
  function cellsFor(r, c, ship) { return Array.from({ length: ship.size }, (_, i) => ({ row: r + (horizontal ? 0 : i), col: c + (horizontal ? i : 0) })); }
  function valid(board, cells) { return cells.every(cell => inside(cell.row, cell.col) && !board[cell.row][cell.col].ship); }
  function put(board, ship, cells) { ship.cells = cells; cells.forEach(cell => { board[cell.row][cell.col].ship = ship; }); }
  function place(r, c) { if (phase !== 'setup' || selectedShip === -1) return; const ship = ships[setupPlayer][selectedShip]; const cells = cellsFor(r, c, ship); if (!valid(boards[setupPlayer], cells)) { status('That ship will not fit there.'); return; } put(boards[setupPlayer], ship, cells); selectedShip = ships[setupPlayer].findIndex(item => !item.cells.length); if (selectedShip !== -1) { render(); status(`Player ${setupPlayer + 1}: place ${ships[setupPlayer][selectedShip].name}.`); return; } if (mode === 'computer') startBattle(); else if (setupPlayer === 0) { phase = 'handoff-setup'; render(); status('Player 1 fleet hidden. Pass the device to Player 2.'); } else { turn = 0; phase = 'handoff-turn'; render(); status('Both fleets are hidden. Pass the device to Player 1 to begin combat.'); } }
  function continueHandoff() { if (phase === 'handoff-setup') { setupPlayer = 1; selectedShip = 0; phase = 'setup'; render(); status('Player 2: place your fleet.'); } else if (phase === 'handoff-turn') { phase = 'playing'; render(); status(`Player ${turn + 1}: choose a target.`); } }
  function startBattle() { phase = 'playing'; turn = 0; render(); status('Player 1: choose a target.'); }
  function randomFleet(index) { boards[index] = makeBoard(); ships[index] = makeShips(); ships[index].forEach(ship => { let cells; do { horizontal = Math.random() > .5; cells = cellsFor(Math.floor(Math.random() * SIZE), Math.floor(Math.random() * SIZE), ship); } while (!valid(boards[index], cells)); put(boards[index], ship, cells); }); horizontal = true; }
  function resetPlacement() { if (phase !== 'setup') return; boards[setupPlayer] = makeBoard(); ships[setupPlayer] = makeShips(); selectedShip = 0; render(); }
  function fire(r, c) { if (phase !== 'playing') return; const defender = turn === 0 ? 1 : 0; const cell = boards[defender][r][c]; if (cell.shot) return; cell.shot = true; const hit = Boolean(cell.ship); const sunk = hit && isSunk(cell.ship, defender); if (allSunk(defender)) { finish(turn); return; } const result = hit ? (sunk ? `Hit and sunk ${cell.ship.name}!` : 'Hit!') : 'Miss.'; if (mode === 'computer' && turn === 0) { phase = 'computer-turn'; render(); status(`${result} Computer is choosing a target.`); computerTimer = setTimeout(computerTurn, 500); return; } turn = defender; phase = 'handoff-turn'; render(); status(`${result} Pass the device to Player ${turn + 1}.`); }
  function computerTurn() { if (phase !== 'computer-turn') return; computerTargets = computerTargets.filter(target => !boards[0][target.r][target.c].shot); const options = []; boards[0].forEach((line, r) => line.forEach((cell, c) => { if (!cell.shot) options.push({ r, c }); })); const target = computerTargets.shift() || options[Math.floor(Math.random() * options.length)]; const cell = boards[0][target.r][target.c]; cell.shot = true; if (cell.ship && !isSunk(cell.ship, 0)) [[-1, 0], [1, 0], [0, -1], [0, 1]].forEach(([dr, dc]) => { const next = { r: target.r + dr, c: target.c + dc }; if (inside(next.r, next.c) && !boards[0][next.r][next.c].shot && !computerTargets.some(item => item.r === next.r && item.c === next.c)) computerTargets.push(next); }); if (allSunk(0)) { finish(1); return; } turn = 0; phase = 'playing'; render(); status(`${cell.ship ? 'Computer hit your fleet.' : 'Computer missed.'} Player 1: choose a target.`); }
  function isSunk(ship, boardIndex) { ship.sunk = ship.cells.every(cell => boards[boardIndex][cell.row][cell.col].shot); return ship.sunk; }
  function allSunk(index) { return ships[index].every(ship => isSunk(ship, index)); }
  function finish(winner) { phase = 'over'; clearTimeout(computerTimer); if (mode === 'two') Storage.updateMultiplayerStats('battleship', winner === 0 ? 'player1' : 'player2'); else { Storage.updateStats('battleship', winner === 0); if (winner === 0) Storage.saveHighScore('battleship', (Storage.getHighScore('battleship') || 0) + 1); } render(); status(`${mode === 'computer' && winner === 1 ? 'Computer' : `Player ${winner + 1}`} wins by sinking every ship.`); }
  function render() { const setup = phase === 'setup'; const own = setup ? setupPlayer : turn; const enemy = own === 0 ? 1 : 0; const privateHandoff = ['handoff-setup', 'handoff-turn'].includes(phase); document.getElementById('fleet-picker').hidden = !setup; document.querySelectorAll('.setup-only').forEach(item => { item.hidden = !setup; }); document.getElementById('continue').hidden = !privateHandoff; document.getElementById('continue').textContent = phase === 'handoff-setup' ? 'Player 2: Continue Setup' : `Player ${turn + 1}: Continue`; document.querySelector('.battle-boards').hidden = privateHandoff; document.getElementById('own-heading').textContent = `Player ${own + 1} fleet`; document.getElementById('target-heading').textContent = mode === 'computer' && own === 0 ? 'Computer waters' : `Player ${enemy + 1} waters`; document.getElementById('victories').textContent = Storage.getHighScore('battleship') || 0; document.getElementById('enemy-left').textContent = ships[enemy].filter(ship => !isSunk(ship, enemy)).length; renderPicker(); renderBoard('player-board', boards[own], true, setup); renderBoard('enemy-board', boards[enemy], false, false); }
  function renderPicker() { const picker = document.getElementById('fleet-picker'); picker.innerHTML = ''; if (phase !== 'setup') return; ships[setupPlayer].forEach((ship, index) => { const button = document.createElement('button'); button.type = 'button'; button.textContent = `${ship.name} (${ship.size})`; button.disabled = !!ship.cells.length; button.className = selectedShip === index ? 'selected' : ''; button.onclick = () => { selectedShip = index; render(); }; picker.appendChild(button); }); }
  function renderBoard(id, board, own, setup) { const element = document.getElementById(id); element.innerHTML = ''; board.forEach((line, r) => line.forEach((cell, c) => { const button = document.createElement('button'); button.type = 'button'; const sunk = cell.ship && isSunk(cell.ship, boards.indexOf(board)); button.className = `battle-cell${own && cell.ship ? ' ship' : ''}${cell.shot && !cell.ship ? ' miss' : ''}${cell.shot && cell.ship ? ' hit' : ''}${sunk ? ' sunk' : ''}`; button.textContent = cell.shot ? (cell.ship ? 'X' : 'o') : (own && cell.ship ? '#' : ''); button.disabled = own ? !setup : phase !== 'playing' || cell.shot; button.setAttribute('aria-label', own ? `Your fleet row ${r + 1}, column ${c + 1}` : `Fire at row ${r + 1}, column ${c + 1}`); button.onclick = () => own ? place(r, c) : fire(r, c); element.appendChild(button); })); }
  function status(message) { document.getElementById('battle-status').textContent = message; }
  function setup() { document.getElementById('backToHub').href = '/'; document.getElementById('new-game').onclick = newGame; document.getElementById('mode-select').onchange = newGame; document.getElementById('rotate').onclick = () => { horizontal = !horizontal; document.getElementById('rotate').textContent = `Rotate: ${horizontal ? 'Horizontal' : 'Vertical'}`; }; document.getElementById('randomize').onclick = () => { if (phase !== 'setup') return; randomFleet(setupPlayer); selectedShip = -1; if (mode === 'computer') startBattle(); else if (setupPlayer === 0) { phase = 'handoff-setup'; render(); status('Player 1 fleet hidden. Pass the device to Player 2.'); } else { turn = 0; phase = 'handoff-turn'; render(); status('Both fleets are hidden. Pass the device to Player 1 to begin combat.'); } }; document.getElementById('reset-placement').onclick = resetPlacement; document.getElementById('continue').onclick = continueHandoff; newGame(); }
  function cleanup() { clearTimeout(computerTimer); }
  window.addEventListener('pagehide', cleanup);
  window.addEventListener('pageshow', event => { if (event.persisted) newGame(); });
  window.initGame = newGame; window.restartGame = newGame; window.cleanupGame = cleanup; if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', setup, { once: true }); else setup();
})();
