const assert=require('assert');const fs=require('fs');const vm=require('vm');function load(files,name,extras={}){const sandbox={console,Math,...extras};sandbox.window=sandbox;files.forEach(file=>vm.runInNewContext(`${fs.readFileSync(file,'utf8')}\nthis.__value=typeof ${name}!=='undefined'?${name}:this.__value;`,sandbox,{filename:file}));return sandbox.__value;}
const Reversi=load(['games/reversi/reversi-rules.js'],'ReversiRules');let r=Reversi.createState();assert.deepStrictEqual(Array.from(Reversi.legalMoves(r),m=>[m.row,m.col]),[[2,3],[3,2],[4,5],[5,4]]);assert(Reversi.applyMove(r,{type:'place',player:'black',row:2,col:3}));assert.strictEqual(r.board[3][3],'black');assert(Reversi.legalMoves(r).length);assert(Reversi.chooseAiMove(r));const pass={board:Array.from({length:8},()=>Array(8).fill('black')),currentPlayer:'white',passes:0,over:false};Reversi.advancePasses(pass);assert(pass.over);
const Mancala=load(['games/mancala/mancala-rules.js'],'MancalaRules');let m=Mancala.createState();let outcome=Mancala.applyMove(m,{type:'sow',player:0,pit:2});assert(outcome.bonus);assert.strictEqual(m.currentPlayer,0);m={pits:[0,0,1,0,0,0,0,0,0,4,0,0,1,0],currentPlayer:0,over:false,winner:null};Mancala.applyMove(m,{type:'sow',player:0,pit:2});assert.strictEqual(m.pits[6],5);assert(Mancala.chooseAiMove({...Mancala.createState(),currentPlayer:1})>=7);
const cardsSandbox={};vm.runInNewContext(`${fs.readFileSync('js/cards.js','utf8')}\nthis.PlayingCards=PlayingCards;`,cardsSandbox);const Gin=load(['games/gin-rummy/gin-rummy-rules.js'],'GinRummyRules',{PlayingCards:cardsSandbox.PlayingCards});const C=(suit,rank)=>new cardsSandbox.PlayingCards.Card(suit,rank);let hand=[C('hearts','3'),C('hearts','4'),C('hearts','5'),C('clubs','king'),C('diamonds','king'),C('spades','king'),C('clubs','2'),C('diamonds','7'),C('spades','9'),C('clubs','ace')];assert.strictEqual(Gin.evaluate(hand).deadwood,19);assert.strictEqual(Gin.evaluate(hand.slice(0,6)).deadwood,0);let deck=cardsSandbox.PlayingCards.createStandardDeck();let g=Gin.createState(deck);assert.strictEqual(g.hands[0].length,10);assert(Gin.draw(g,{type:'draw',player:0,source:'stock'}));assert(!Gin.discard(g,{type:'discard',player:0,cardId:g.drawnFrom}));
const Falling=load(['games/falling-blocks/falling-blocks-rules.js'],'FallingBlocksRules');let board=Falling.createBoard();assert(!Falling.collides(board,Falling.piece('T')));let p=Falling.piece('I');p.x=-2;assert(Falling.collides(board,p));board[19].fill('I');assert.strictEqual(Falling.clearLines(board),1);assert.strictEqual(Falling.scoreFor(4,0),800);assert.strictEqual(Falling.rotate(Falling.piece('T')).cells.length,4);
const Brick=load(['games/brick-breaker/brick-breaker-rules.js'],'BrickBreakerRules');let ball={x:15,y:10,r:5,vx:20,vy:0},brick={x:15,y:5,w:20,h:20};assert(Brick.circleRect(ball,brick));assert(Brick.reflectBrick(ball,brick));assert.strictEqual(ball.vx,-20);assert(Brick.createBricks(1).length>0);
const Darts=load(['games/darts/darts-rules.js'],'DartsRules');assert.strictEqual(Darts.scoreAt(0,0).score,50);assert.strictEqual(Darts.scoreAt(0,-120,200).score,60);let d=Darts.createState('301',2);d.scores[0]=10;Darts.throwDart(d,{score:12,label:'12',number:12});assert.strictEqual(d.scores[0],10);assert.strictEqual(d.currentPlayer,1);d.scores[1]=20;assert(Darts.throwDart(d,{score:20,label:'20',number:20}).win);
const Shuffle=load(['games/shuffleboard/shuffleboard-rules.js'],'ShuffleboardRules');assert.strictEqual(Shuffle.zoneScore(70,760),4);assert.deepStrictEqual(Array.from(Shuffle.roundScore([{player:0,y:70,out:false},{player:1,y:250,out:false}])),[4,2]);assert.strictEqual(Shuffle.applyRound([12,2],[4,0]),0);assert(Shuffle.stable([{x:1,y:1,vx:0,vy:0}]));
const Pool=load(['games/pool/pool-rules.js'],'PoolRules');let ps=Pool.createState();Pool.resolveTurn(ps,['solid'],{solid:6,stripe:7});assert.deepStrictEqual(Array.from(ps.groups),['solid','stripe']);assert.strictEqual(ps.currentPlayer,0);Pool.resolveTurn(ps,[],{solid:6,stripe:7});assert.strictEqual(ps.currentPlayer,1);ps.currentPlayer=0;Pool.resolveTurn(ps,['eight'],{solid:0,stripe:7});assert.strictEqual(ps.winner,0);assert(Pool.allStopped([{active:true,x:0,y:0,vx:0,vy:0}]));
const Physics=load(['js/physics.js'],'Physics2D',{requestAnimationFrame(){},cancelAnimationFrame(){},performance:{now:()=>0}});let a={x:0,y:0,r:10,vx:10,vy:0},b={x:15,y:0,r:10,vx:-10,vy:0};assert(Physics.collideCircles(a,b));assert(a.vx<0&&b.vx>0);Physics.integrate(a,.1,1);assert(Number.isFinite(a.x+a.y+a.vx+a.vy));console.log('expansion game tests passed');
