const FallingBlocks=(()=>{const canvas=document.getElementById('game-canvas'),ctx=canvas.getContext('2d'),timer=Storage.createPlayTimer('falling-blocks'),types=Object.keys(FallingBlocksRules.shapes),colors={I:'#49b6c8',O:'#e3a34b',T:'#a777c9',L:'#dc7355',J:'#5c83d6',S:'#7fba85',Z:'#dd6b61'};let board,current,next,held,canHold,score,lines,over,lastDrop,frame;const randomType=()=>types[Math.floor(Math.random()*types.length)];
function initialise(){cancelAnimationFrame(frame);GameUI.clearGameOver();timer.reset();board=FallingBlocksRules.createBoard();next=FallingBlocksRules.piece(randomType());held=null;score=lines=0;over=false;spawn();lastDrop=performance.now();timer.start();loop(lastDrop);}
function spawn(type){current=type?FallingBlocksRules.piece(type):next;next=FallingBlocksRules.piece(randomType());canHold=true;if(FallingBlocksRules.collides(board,current))finish();update();}
function move(dx,dy){const candidate={...current,x:current.x+dx,y:current.y+dy};if(!FallingBlocksRules.collides(board,candidate)){current=candidate;return true;}if(dy>0)lock();return false;}
function turn(){let candidate=FallingBlocksRules.rotate(current);for(const kick of [0,-1,1,-2,2]){candidate.x=current.x+kick;if(!FallingBlocksRules.collides(board,candidate)){current=candidate;break;}}}
function lock(){FallingBlocksRules.merge(board,current);const cleared=FallingBlocksRules.clearLines(board);lines+=cleared;score+=FallingBlocksRules.scoreFor(cleared,level());spawn();}
function hardDrop(){let distance=0;while(move(0,1))distance++;score+=distance*2;}
function hold(){if(!canHold)return;const type=held;held=current.type;canHold=false;if(type)current=FallingBlocksRules.piece(type);else{current=next;next=FallingBlocksRules.piece(randomType());}if(FallingBlocksRules.collides(board,current))finish();update();}
function level(){return Math.floor(lines/10);}function ghost(){const copy={...current};while(!FallingBlocksRules.collides(board,{...copy,y:copy.y+1}))copy.y++;return copy;}
function loop(time){if(over)return;const delay=Math.max(90,750-level()*65);if(time-lastDrop>=delay){move(0,1);lastDrop=time;}draw();frame=requestAnimationFrame(loop);}
function drawPiece(piece,alpha=1){ctx.globalAlpha=alpha;piece.cells.forEach(([x,y])=>{const px=x+piece.x,py=y+piece.y;if(py<0)return;ctx.fillStyle=colors[piece.type];ctx.fillRect(px*30+1,py*30+1,28,28);});ctx.globalAlpha=1;}function draw(){ctx.clearRect(0,0,300,600);board.forEach((row,y)=>row.forEach((cell,x)=>{if(cell){ctx.fillStyle=colors[cell];ctx.fillRect(x*30+1,y*30+1,28,28);}}));drawPiece(ghost(),.2);drawPiece(current);}
function finish(){if(over)return;over=true;cancelAnimationFrame(frame);timer.stop();Storage.recordResult('falling-blocks','complete');Storage.saveHighScore('falling-blocks',score);update();GameUI.showGameOver({title:'Stack topped out',message:`Score ${score} · ${lines} lines`,onRestart:initialise});}
function action(name){if(over)return;if(name==='left')move(-1,0);if(name==='right')move(1,0);if(name==='down'){if(move(0,1))score++;}if(name==='rotate')turn();if(name==='drop')hardDrop();if(name==='hold')hold();draw();update();}
function update(){const s=Storage.getStats('falling-blocks');document.getElementById('games-played').textContent=s.gamesPlayed;document.getElementById('high-score').textContent=Storage.getHighScore('falling-blocks')??0;document.getElementById('time-played').textContent=`${Math.floor(s.timePlayed/60)}m ${s.timePlayed%60}s`;document.getElementById('score').textContent=score;document.getElementById('level').textContent=level()+1;document.getElementById('next-piece').textContent=next?.type||'—';document.getElementById('hold-piece').textContent=held||'—';document.getElementById('falling-status').textContent=over?`Game over. Score ${score}.`:`Level ${level()+1}. ${lines} lines cleared.`;}
function setup(){document.querySelector('.restart-btn').onclick=initialise;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.addEventListener('keydown',e=>{const map={ArrowLeft:'left',ArrowRight:'right',ArrowDown:'down',ArrowUp:'rotate',' ':'drop',c:'hold',C:'hold'};if(map[e.key]){e.preventDefault();action(map[e.key]);}});window.addEventListener('pagehide',()=>{cancelAnimationFrame(frame);timer.stop();});window.addEventListener('pageshow',event=>{if(event.persisted)initialise();});initialise();}window.initGame=window.restartGame=initialise;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();})();
