const Shuffleboard=(()=>{const canvas=document.getElementById('game-canvas'),ctx=canvas.getContext('2d'),timer=Storage.createPlayTimer('shuffleboard');let pucks,scores,shot,moving,drag,loop;const start={x:210,y:700};function initialise(){loop?.stop();GameUI.clearGameOver();timer.reset();scores=[0,0];newRound();}
function newRound(){pucks=[];shot=0;moving=false;drag=null;loop=Physics2D.createFixedLoop(simulate,draw);loop.start();update();}
function simulate(dt){if(!moving)return;for(const puck of pucks){Physics2D.integrate(puck,dt,1.15);if(puck.x-puck.r<12||puck.x+puck.r>408){puck.x=Math.max(12+puck.r,Math.min(408-puck.r,puck.x));puck.vx*=-.82;}if(puck.y<-puck.r||puck.y>760+puck.r){puck.out=true;puck.vx=puck.vy=0;}}for(let i=0;i<pucks.length;i++)for(let j=i+1;j<pucks.length;j++)if(!pucks[i].out&&!pucks[j].out)Physics2D.collideCircles(pucks[i],pucks[j],.88);if(ShuffleboardRules.stable(pucks)){moving=false;shot++;if(shot===8)finishRound();else update();}}
function finishRound(){const points=ShuffleboardRules.roundScore(pucks);const winner=ShuffleboardRules.applyRound(scores,points);update();if(winner!==undefined){loop.stop();timer.stop();Storage.recordResult('shuffleboard',winner===0?'win':'loss');renderStats();GameUI.showGameOver({title:`Player ${winner+1} wins!`,message:`Match ${scores[0]}–${scores[1]}`,onRestart:initialise});}else setTimeout(newRound,900);}
function pointer(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*420/rect.width,y:(event.clientY-rect.top)*760/rect.height};}function down(event){if(moving||shot>=8)return;const point=pointer(event);if(Math.hypot(point.x-start.x,point.y-start.y)<60){drag={start:point,current:point};canvas.setPointerCapture(event.pointerId);}}function move(event){if(drag)drag.current=pointer(event);}function up(event){if(!drag)return;const point=pointer(event),dx=point.x-drag.start.x,dy=point.y-drag.start.y;drag=null;if(dy>-15)return;const magnitude=Math.min(700,Math.hypot(dx,dy)*3.2);const length=Math.hypot(dx,dy)||1;pucks.push({x:start.x,y:start.y,r:17,vx:dx/length*magnitude,vy:dy/length*magnitude,player:ShuffleboardRules.nextPlayer(shot),out:false});timer.start();moving=true;update();}
function draw(){ctx.clearRect(0,0,420,760);ctx.strokeStyle='#f7f1e899';ctx.lineWidth=2;[[.17,'4'],[.29,'3'],[.41,'2'],[.53,'1']].forEach(([ratio,label])=>{ctx.beginPath();ctx.moveTo(12,760*ratio);ctx.lineTo(408,760*ratio);ctx.stroke();ctx.fillStyle='#f7f1e8';ctx.font='bold 22px sans-serif';ctx.fillText(label,25,760*ratio-8);});pucks.filter(p=>!p.out).forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=p.player?'#dc7355':'#e3a34b';ctx.fill();ctx.strokeStyle='#171512';ctx.stroke();});if(!moving&&shot<8){ctx.beginPath();ctx.arc(start.x,start.y,17,0,Math.PI*2);ctx.fillStyle=ShuffleboardRules.nextPlayer(shot)?'#dc7355':'#e3a34b';ctx.fill();}if(drag){ctx.beginPath();ctx.moveTo(drag.start.x,drag.start.y);ctx.lineTo(drag.current.x,drag.current.y);ctx.strokeStyle='#f7f1e8';ctx.lineWidth=3;ctx.stroke();}}
function update(){document.getElementById('turn-indicator').textContent=moving?'Pucks moving…':`Player ${ShuffleboardRules.nextPlayer(shot)+1} · Puck ${Math.floor(shot/2)+1}`;document.getElementById('match-score').textContent=`${scores[0]}–${scores[1]}`;document.getElementById('status').textContent=moving?'Let the pucks settle.':'Drag the waiting puck toward the scoring end.';renderStats();}
function renderStats(){const s=Storage.getStats('shuffleboard');for(const k of ['gamesPlayed','wins','losses'])document.getElementById(k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())).textContent=s[k];document.getElementById('time-played').textContent=`${Math.floor(s.timePlayed/60)}m ${s.timePlayed%60}s`;}
function setup(){document.querySelector('.restart-btn').onclick=initialise;canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',()=>drag=null);window.addEventListener('pagehide',()=>{loop?.stop();timer.stop();});initialise();}window.initGame=window.restartGame=initialise;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();})();
