const Pool=(()=>{const canvas=document.getElementById('game-canvas'),ctx=canvas.getContext('2d'),timer=Storage.createPlayTimer('pool'),pockets=[[30,30],[450,25],[870,30],[30,470],[450,475],[870,470]];let balls,state,aim={x:700,y:250},moving,events,loop;const palette=['#fff','#e5b52d','#2764aa','#c34236','#74449a','#e77726','#28865d','#7a2d25','#171512','#e5b52d','#2764aa','#c34236','#74449a','#e77726','#28865d','#7a2d25'];
function rack(){loop?.stop();GameUI.clearGameOver();timer.reset();state=PoolRules.createState();balls=[ball(0,230,250)];const order=[1,9,2,10,8,3,11,4,12,5,13,6,14,7,15];let index=0;for(let row=0;row<5;row++)for(let col=0;col<=row;col++)balls.push(ball(order[index++],625+row*29,250-row*15+col*30));moving=false;events=[];loop=Physics2D.createFixedLoop(simulate,draw);loop.start();update();}
function ball(number,x,y){return{number,x,y,r:12,vx:0,vy:0,active:true};}
function simulate(dt){if(!moving)return;for(const b of balls.filter(item=>item.active)){Physics2D.integrate(b,dt,.65);for(const [px,py] of pockets)if(b.active&&Math.hypot(b.x-px,b.y-py)<25){b.active=false;b.vx=b.vy=0;events.push(b.number===0?'scratch':PoolRules.ballGroup(b.number));}if(!b.active)continue;if(b.x-b.r<32||b.x+b.r>868){b.x=Math.max(32+b.r,Math.min(868-b.r,b.x));b.vx*=-.86;}if(b.y-b.r<32||b.y+b.r>468){b.y=Math.max(32+b.r,Math.min(468-b.r,b.y));b.vy*=-.86;}}const active=balls.filter(b=>b.active);for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++)Physics2D.collideCircles(active[i],active[j],.94);if(PoolRules.allStopped(balls)){moving=false;finishShot();}}
function finishShot(){const remaining={solid:balls.filter(b=>b.active&&PoolRules.ballGroup(b.number)==='solid').length,stripe:balls.filter(b=>b.active&&PoolRules.ballGroup(b.number)==='stripe').length};PoolRules.resolveTurn(state,events,remaining);const cue=balls[0];if(!cue.active){cue.active=true;cue.x=230;cue.y=250;cue.vx=cue.vy=0;separateCue(cue);}events=[];update();if(state.over)finish();}
function separateCue(cue){for(let attempt=0;attempt<20&&balls.some(b=>b!==cue&&b.active&&Math.hypot(b.x-cue.x,b.y-cue.y)<b.r+cue.r);attempt++)cue.x-=18;cue.x=Math.max(50,cue.x);}
function shoot(){if(moving||state.over)return;const cue=balls[0];if(!cue.active)return;const dx=aim.x-cue.x,dy=aim.y-cue.y,length=Math.hypot(dx,dy);if(length<5)return;const speed=Number(document.getElementById('power').value)*8;cue.vx=dx/length*speed;cue.vy=dy/length*speed;events=[];timer.start();moving=true;update();}
function pointer(event){const rect=canvas.getBoundingClientRect();aim={x:(event.clientX-rect.left)*900/rect.width,y:(event.clientY-rect.top)*500/rect.height};draw();}
function draw(){ctx.clearRect(0,0,900,500);ctx.fillStyle='#185744';ctx.fillRect(28,28,844,444);ctx.strokeStyle='#b8894c';ctx.lineWidth=25;ctx.strokeRect(16,16,868,468);pockets.forEach(([x,y])=>{ctx.beginPath();ctx.arc(x,y,25,0,Math.PI*2);ctx.fillStyle='#090806';ctx.fill();});balls.filter(b=>b.active).forEach(b=>{ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fillStyle=palette[b.number];ctx.fill();if(b.number>8){ctx.strokeStyle='#fff';ctx.lineWidth=5;ctx.stroke();}ctx.fillStyle=b.number===0?'transparent':b.number===8?'#fff':'#171512';ctx.font='bold 8px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';if(b.number)ctx.fillText(b.number,b.x,b.y);});if(!moving&&!state.over){const cue=balls[0],dx=aim.x-cue.x,dy=aim.y-cue.y,len=Math.hypot(dx,dy)||1;ctx.setLineDash([8,7]);ctx.beginPath();ctx.moveTo(cue.x,cue.y);ctx.lineTo(cue.x+dx/len*260,cue.y+dy/len*260);ctx.strokeStyle='#fff9';ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([]);}}
function finish(){loop.stop();timer.stop();Storage.recordResult('pool',state.winner===0?'win':'loss');renderStats();GameUI.showGameOver({title:`Player ${state.winner+1} wins!`,message:'The 8 ball is down.',onRestart:rack});}
function update(){const labels=state.groups.map(group=>group?group[0].toUpperCase()+group.slice(1):'Open');document.getElementById('turn-indicator').textContent=moving?'Balls moving…':`Player ${state.currentPlayer+1}`;document.getElementById('groups').textContent=`Player 1: ${labels[0]} · Player 2: ${labels[1]}`;document.getElementById('status').textContent=moving?'Shot in progress…':'Aim, set power, and shoot.';document.getElementById('shoot').disabled=moving||state.over;renderStats();}
function renderStats(){const s=Storage.getStats('pool');for(const k of ['gamesPlayed','wins','losses'])document.getElementById(k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())).textContent=s[k];document.getElementById('time-played').textContent=`${Math.floor(s.timePlayed/60)}m ${s.timePlayed%60}s`;}
function setup(){document.querySelector('.restart-btn').onclick=rack;document.getElementById('shoot').onclick=shoot;canvas.addEventListener('pointerdown',pointer);canvas.addEventListener('pointermove',e=>{if(e.buttons)pointer(e);});window.addEventListener('pagehide',()=>{loop?.stop();timer.stop();});window.addEventListener('pageshow',event=>{if(event.persisted)rack();});rack();}window.initGame=window.restartGame=rack;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();})();
