const Minesweeper = (() => {
  const difficulties = { beginner: [9, 9, 10], intermediate: [16, 16, 40], expert: [16, 30, 99] };
  let rows, cols, mines, board, flags, firstClick, active, seconds, timerId, difficulty, mode, currentPlayer, scores, flagMode;
  function initialise(nextDifficulty) { mode = document.getElementById('mode-select').value; difficulty = nextDifficulty || document.getElementById('difficulty-select').value; if (mode === 'duel') difficulty = 'beginner'; [rows, cols, mines] = difficulties[difficulty]; clearInterval(timerId); board = Array.from({ length: rows }, () => Array.from({ length: cols }, () => ({ mine: false, revealed: false, flagged: false, count: 0 }))); flags = 0; firstClick = true; active = true; seconds = 0; currentPlayer = 1; scores = [0, 0]; flagMode = false; document.getElementById('difficulty-select').value = difficulty; document.getElementById('difficulty-select').disabled = mode === 'duel'; render(); updateUI(); }
  const inside = (row, col) => row >= 0 && row < rows && col >= 0 && col < cols;
  function neighbours(row, col) { const result = []; for (let dr = -1; dr <= 1; dr++) for (let dc = -1; dc <= 1; dc++) if ((dr || dc) && inside(row + dr, col + dc)) result.push([row + dr, col + dc]); return result; }
  function plantMines(row, col) { const excluded = new Set(neighbours(row, col).concat([[row, col]]).map(cell => cell.join(','))); const choices = []; board.forEach((line, r) => line.forEach((cell, c) => { if (!excluded.has(`${r},${c}`)) choices.push([r, c]); })); choices.sort(() => Math.random() - .5).slice(0, mines).forEach(([r, c]) => { board[r][c].mine = true; }); board.forEach((line, r) => line.forEach((cell, c) => { cell.count = cell.mine ? 0 : neighbours(r, c).filter(([nr, nc]) => board[nr][nc].mine).length; })); }
  function reveal(row, col) { const first = board[row][col]; if (!active || first.flagged || first.revealed) return; if (firstClick) { plantMines(row, col); firstClick = false; timerId = setInterval(() => { seconds++; updateUI(); }, 1000); } const cell = board[row][col]; if (cell.mine) { if (mode === 'duel') { cell.revealed = true; scores[currentPlayer - 1] -= 3; currentPlayer = currentPlayer === 1 ? 2 : 1; render(); updateUI('Mine! -3 points; turn passes.'); return; } finish(false); return; } let earned = 0; const queue = [[row, col]]; while (queue.length) { const [r, c] = queue.pop(); const next = board[r][c]; if (next.revealed || next.flagged || next.mine) continue; next.revealed = true; earned++; if (!next.count) neighbours(r, c).forEach(([nr, nc]) => queue.push([nr, nc])); } if (mode === 'duel') { scores[currentPlayer - 1] += earned; currentPlayer = currentPlayer === 1 ? 2 : 1; } if (board.flat().filter(item => item.revealed && !item.mine).length === rows * cols - mines) finish(true); else { render(); updateUI(mode === 'duel' ? `+${earned} safe cells.` : ''); } }
  function toggleFlag(row, col) { if (mode === 'duel') return; const cell = board[row][col]; if (!active || cell.revealed || (!cell.flagged && flags === mines)) return; cell.flagged = !cell.flagged; flags += cell.flagged ? 1 : -1; render(); updateUI(); }
  function render() { const element = document.getElementById('game-board'); element.className = 'minesweeper-board'; element.style.gridTemplateColumns = `repeat(${cols}, 1fr)`; element.innerHTML = ''; board.forEach((line, row) => line.forEach((cell, col) => { const button = document.createElement('button'); button.type = 'button'; button.className = `cell ${cell.revealed ? 'revealed' : 'hidden'}${cell.flagged ? ' flagged' : ''}${cell.revealed && cell.mine ? ' mine' : ''}${cell.revealed && cell.count ? ` revealed-number-${cell.count}` : ''}`; button.textContent = cell.revealed ? (cell.mine ? '*' : cell.count || '') : ''; button.setAttribute('aria-label', cell.revealed ? (cell.mine ? 'Mine' : `${cell.count || 'Empty'} neighbouring mines`) : cell.flagged ? 'Flagged cell' : 'Covered cell'); button.onclick = () => flagMode && mode !== 'duel' ? toggleFlag(row, col) : reveal(row, col); button.oncontextmenu = event => { event.preventDefault(); toggleFlag(row, col); }; element.appendChild(button); })); }
  function format(value) { return `${Math.floor(value / 60)}:${String(value % 60).padStart(2, '0')}`; }
  function updateUI(message) { document.getElementById('timer').textContent = format(seconds); document.getElementById('mine-count').textContent = mines; document.getElementById('flags-left').textContent = mode === 'duel' ? 'Disabled' : mines - flags; document.getElementById('best-time').textContent = Storage.getBestScore('minesweeper') === null ? '--:--' : format(Storage.getBestScore('minesweeper')); document.getElementById('player-one-score').textContent = mode === 'duel' ? scores[0] : '-'; document.getElementById('player-two-score').textContent = mode === 'duel' ? scores[1] : '-'; const flagButton = document.getElementById('flag-mode'); flagButton.hidden = mode === 'duel'; flagButton.classList.toggle('active', flagMode); flagButton.setAttribute('aria-pressed', String(flagMode)); flagButton.textContent = `Flag mode: ${flagMode ? 'On' : 'Off'}`; document.getElementById('mine-status').textContent = message || (mode === 'duel' ? `Player ${currentPlayer}'s turn. Safe cells score +1; mines cost -3.` : flagMode ? 'Flag mode is on. Tap a covered cell to add or remove a flag.' : 'Reveal mode. Tap a covered cell to reveal it; use Flag mode to mark mines.'); }
  function finish(won) { active = false; clearInterval(timerId); let title; if (mode === 'duel') { const result = scores[0] === scores[1] ? 'draw' : scores[0] > scores[1] ? 'player1' : 'player2'; Storage.updateMultiplayerStats('minesweeper', result); title = result === 'draw' ? 'Duel draw!' : `${result === 'player1' ? 'Player 1' : 'Player 2'} wins the Duel!`; } else { if (won) { Storage.saveBestScore('minesweeper', seconds); Storage.updateStats('minesweeper', true); } else { board.flat().filter(cell => cell.mine).forEach(cell => { cell.revealed = true; }); Storage.updateStats('minesweeper', false); } title = won ? 'Victory!' : 'Game over'; } render(); updateUI(); const modal = document.createElement('div'); modal.className = 'game-over-modal'; modal.innerHTML = `<div class="modal-content"><h2>${title}</h2><p>${mode === 'duel' ? `Player 1: ${scores[0]} · Player 2: ${scores[1]}` : `Time: ${format(seconds)}`}</p><button class="game-btn btn-primary">Play Again</button></div>`; modal.querySelector('button').onclick = () => { modal.remove(); initialise(difficulty); }; document.body.appendChild(modal); }
  function setup() { document.getElementById('backToHub').href = '/'; const flagButton = document.createElement('button'); flagButton.id = 'flag-mode'; flagButton.type = 'button'; flagButton.className = 'btn-secondary game-btn'; document.querySelector('.game-controls').insertBefore(flagButton, document.querySelector('.game-controls label')); flagButton.onclick = () => { if (mode !== 'duel') { flagMode = !flagMode; updateUI(); } }; document.querySelectorAll('.restart-btn').forEach(button => button.onclick = () => initialise(difficulty)); document.getElementById('difficulty-select').onchange = event => initialise(event.target.value); document.getElementById('mode-select').onchange = () => initialise(); initialise(); }
  window.initGame = initialise; window.restartGame = () => initialise(difficulty); window.cleanupGame = () => clearInterval(timerId); if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', setup, { once: true }); else setup();
})();
