const Reversi = (() => {
  const timer = Storage.createPlayTimer('reversi'); let state; let aiTimer;
  const mode = () => document.getElementById('mode-select').value;
  function initialise() { clearTimeout(aiTimer); timer.reset(); GameUI.clearGameOver(); state = ReversiRules.createState(); render(); }
  function play(row, col, ai = false) { if (state.over || (mode() === 'computer' && state.currentPlayer === 'white' && !ai)) return; timer.start(); if (!ReversiRules.applyMove(state, { type: 'place', player: state.currentPlayer, row, col })) return; render(); if (state.over) finish(); else if (mode() === 'computer' && state.currentPlayer === 'white') aiTimer = setTimeout(() => { const move = ReversiRules.chooseAiMove(state); if (move) play(move.row, move.col, true); }, 260); }
  function finish() { timer.stop(); const score = ReversiRules.counts(state); const result = score.black === score.white ? 'draw' : score.black > score.white ? 'win' : 'loss'; Storage.recordResult('reversi', result); updateStats(); GameUI.showGameOver({ title: result === 'draw' ? 'Draw' : score.black > score.white ? 'Black wins!' : 'White wins!', message: `Black ${score.black} · White ${score.white}`, onRestart: initialise }); }
  function render() { const board = document.getElementById('game-board'); const legal = ReversiRules.legalMoves(state); board.innerHTML = ''; state.board.forEach((line,row) => line.forEach((value,col) => { const button = document.createElement('button'); button.className = `reversi-cell${legal.some(move => move.row === row && move.col === col) ? ' legal' : ''}`; button.disabled = Boolean(value) || state.over; button.setAttribute('aria-label', value ? `${value} disk` : `Row ${row+1}, column ${col+1}${button.classList.contains('legal') ? ', legal move' : ''}`); button.onclick = () => play(row,col); if(value){const disk=document.createElement('span');disk.className=`disk ${value}`;button.appendChild(disk);} board.appendChild(button); })); const count=ReversiRules.counts(state); document.getElementById('black-count').textContent=count.black; document.getElementById('white-count').textContent=count.white; document.getElementById('turn-indicator').textContent=state.currentPlayer==='black'?'Player 1 (Black)':mode()==='computer'?'Computer (White)':'Player 2 (White)'; updateStats(); }
  function updateStats(){const stats=Storage.getStats('reversi');['gamesPlayed','wins','losses','draws'].forEach(key=>document.getElementById(key.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)).textContent=stats[key]);document.getElementById('time-played').textContent=`${Math.floor(stats.timePlayed/60)}m ${stats.timePlayed%60}s`;}
  function setup(){document.querySelector('.restart-btn').onclick=initialise;document.getElementById('mode-select').onchange=initialise;window.addEventListener('pagehide',()=>{clearTimeout(aiTimer);timer.stop();});window.addEventListener('pageshow',event=>{if(event.persisted)initialise();});initialise();} window.initGame=window.restartGame=initialise;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();
})();
