const ReversiRules = (() => {
  const SIZE = 8; const directions = [-1, 0, 1].flatMap(row => [-1, 0, 1].map(col => [row, col])).filter(([row, col]) => row || col);
  function createState() { const board = Array.from({ length: SIZE }, () => Array(SIZE).fill(null)); board[3][3] = board[4][4] = 'white'; board[3][4] = board[4][3] = 'black'; return { board, currentPlayer: 'black', passes: 0, over: false }; }
  const opponent = player => player === 'black' ? 'white' : 'black';
  function flipsFor(board, row, col, player) { if (board[row]?.[col]) return []; const flips = []; for (const [dr, dc] of directions) { const line = []; let r = row + dr; let c = col + dc; while (board[r]?.[c] === opponent(player)) { line.push([r, c]); r += dr; c += dc; } if (line.length && board[r]?.[c] === player) flips.push(...line); } return flips; }
  function legalMoves(state, player = state.currentPlayer) { const moves = []; for (let row = 0; row < SIZE; row++) for (let col = 0; col < SIZE; col++) { const flips = flipsFor(state.board, row, col, player); if (flips.length) moves.push({ row, col, flips }); } return moves; }
  function counts(state) { return state.board.flat().reduce((total, cell) => { if (cell) total[cell]++; return total; }, { black: 0, white: 0 }); }
  function applyMove(state, action) { if (state.over || action.player !== state.currentPlayer) return false; const flips = flipsFor(state.board, action.row, action.col, action.player); if (!flips.length) return false; state.board[action.row][action.col] = action.player; flips.forEach(([row, col]) => state.board[row][col] = action.player); state.currentPlayer = opponent(action.player); state.passes = 0; advancePasses(state); return true; }
  function advancePasses(state) { while (!state.over && !legalMoves(state).length) { state.passes++; if (state.passes === 2) state.over = true; else state.currentPlayer = opponent(state.currentPlayer); } return state; }
  function chooseAiMove(state) { const weights = [[120,-30,18,8,8,18,-30,120],[-30,-45,-8,-8,-8,-8,-45,-30],[18,-8,12,3,3,12,-8,18],[8,-8,3,3,3,3,-8,8],[8,-8,3,3,3,3,-8,8],[18,-8,12,3,3,12,-8,18],[-30,-45,-8,-8,-8,-8,-45,-30],[120,-30,18,8,8,18,-30,120]]; return legalMoves(state).map(move => { const copy = JSON.parse(JSON.stringify(state)); copy.board[move.row][move.col] = state.currentPlayer; move.flips.forEach(([r,c]) => copy.board[r][c] = state.currentPlayer); copy.currentPlayer = opponent(state.currentPlayer); return { move, score: weights[move.row][move.col] + move.flips.length * 2 - legalMoves(copy).length * 3 }; }).sort((a,b) => b.score - a.score)[0]?.move || null; }
  return { SIZE, createState, flipsFor, legalMoves, applyMove, advancePasses, counts, chooseAiMove };
})();
