const MemoryGame = (() => {
  const symbols = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];
  let cards, flipped, pairs, moves, seconds, timerId, matchTimerId, locked, active, mode, currentPlayer, scores;
  function initialise() { clearInterval(timerId); clearTimeout(matchTimerId); GameUI.clearGameOver(); timerId = null; matchTimerId = null; mode = document.getElementById('mode-select').value; cards = [...symbols, ...symbols].sort(() => Math.random() - .5).map((symbol, id) => ({ id, symbol, flipped: false, matched: false })); flipped = []; pairs = moves = seconds = 0; currentPlayer = 1; scores = [0, 0]; locked = false; active = true; render(); updateUI(); }
  function render() { const board = document.getElementById('game-board'); board.className = 'memory-board'; board.innerHTML = ''; cards.forEach(card => { const item = document.createElement('button'); item.type = 'button'; item.className = `card${card.flipped ? ' flipped' : ''}${card.matched ? ' matched' : ''}`; item.setAttribute('aria-label', card.flipped || card.matched ? `Card ${card.symbol}` : 'Face-down card'); item.innerHTML = `<span class="card-inner"><span class="card-front">?</span><span class="card-back">${card.symbol}</span></span>`; item.onclick = () => flip(card); board.appendChild(item); }); }
  function flip(card) { if (!active || locked || card.flipped || card.matched) return; if (mode === 'single' && !timerId) timerId = setInterval(() => { if (active) { seconds++; updateUI(); } }, 1000); card.flipped = true; flipped.push(card); render(); if (flipped.length !== 2) return; moves++; locked = true; const [first, second] = flipped; matchTimerId = setTimeout(() => { matchTimerId = null; if (!active) return; if (first.symbol === second.symbol) { first.matched = second.matched = true; pairs++; if (mode === 'two') scores[currentPlayer - 1]++; } else { first.flipped = second.flipped = false; if (mode === 'two') currentPlayer = currentPlayer === 1 ? 2 : 1; } flipped = []; locked = false; render(); updateUI(); if (pairs === symbols.length) finish(); }, first.symbol === second.symbol ? 450 : 850); }
  function format(value) { return `${Math.floor(value / 60)}:${String(value % 60).padStart(2, '0')}`; }
  function updateUI() { document.getElementById('timer').textContent = format(seconds); document.getElementById('moves').textContent = moves; document.getElementById('pairs-found').textContent = pairs; document.getElementById('best-time').textContent = Storage.getBestScore('memory') === null ? '--:--' : format(Storage.getBestScore('memory')); document.getElementById('player-one-score').textContent = mode === 'two' ? scores[0] : '-'; document.getElementById('player-two-score').textContent = mode === 'two' ? scores[1] : '-'; document.getElementById('memory-status').textContent = mode === 'two' ? `Player ${currentPlayer}'s turn. A match earns a point and another turn.` : 'Find all pairs in the fewest moves and fastest time.'; }
  function finish() { active = false; clearInterval(timerId); let title; if (mode === 'two') { const result = scores[0] === scores[1] ? 'draw' : scores[0] > scores[1] ? 'player1' : 'player2'; Storage.updateMultiplayerStats('memory', result); title = result === 'draw' ? 'Draw!' : `${result === 'player1' ? 'Player 1' : 'Player 2'} wins!`; } else { Storage.saveBestScore('memory', seconds); Storage.updateStats('memory', true); title = 'Victory!'; } GameUI.showGameOver({ title, message: mode === 'two' ? `Player 1: ${scores[0]} pairs · Player 2: ${scores[1]} pairs` : `Time: ${format(seconds)} · Moves: ${moves}`, onRestart: initialise }); }
  function setup() { document.getElementById('backToHub').href = '/'; document.querySelectorAll('.restart-btn').forEach(button => button.onclick = initialise); document.getElementById('mode-select').onchange = initialise; initialise(); }
  function cleanup() { active = false; clearInterval(timerId); clearTimeout(matchTimerId); }
  window.addEventListener('pagehide', cleanup);
  window.addEventListener('pageshow', event => { if (event.persisted) initialise(); });
  window.initGame = initialise; window.restartGame = initialise; window.cleanupGame = cleanup; if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', setup, { once: true }); else setup();
})();
