const BrickBreaker=(()=>{const canvas=document.getElementById('game-canvas'),ctx=canvas.getContext('2d'),timer=Storage.createPlayTimer('brick-breaker');let paddle,balls,bricks,lives,score,level,launched,over,frame,last;const colors=['#dc7355','#e3a34b','#7fba85','#5c83d6','#a777c9','#49b6c8'];
function initialise(){cancelAnimationFrame(frame);GameUI.clearGameOver();timer.reset();lives=3;score=0;level=1;over=false;setupLevel();timer.start();last=performance.now();frame=requestAnimationFrame(loop);}
function setupLevel(){paddle={x:300,y:485,w:120,h:16};balls=[{x:360,y:465,r:8,vx:210+level*12,vy:-250-level*14}];bricks=BrickBreakerRules.createBricks(level);launched=false;update();}
function launch(){if(!over){launched=true;document.getElementById('status').textContent='Ball in play';}}
function simulate(dt){const steps=Math.max(1,Math.ceil(dt/.004));const step=dt/steps;for(let n=0;n<steps;n++)for(const ball of balls){if(!launched){ball.x=paddle.x+paddle.w/2;ball.y=paddle.y-ball.r-2;continue;}ball.x+=ball.vx*step;ball.y+=ball.vy*step;if(ball.x-ball.r<0){ball.x=ball.r;ball.vx=Math.abs(ball.vx);}if(ball.x+ball.r>canvas.width){ball.x=canvas.width-ball.r;ball.vx=-Math.abs(ball.vx);}if(ball.y-ball.r<0){ball.y=ball.r;ball.vy=Math.abs(ball.vy);}if(ball.vy>0&&BrickBreakerRules.circleRect(ball,paddle)){ball.y=paddle.y-ball.r;const offset=(ball.x-(paddle.x+paddle.w/2))/(paddle.w/2);const speed=Math.max(300,Math.hypot(ball.vx,ball.vy));ball.vx=offset*speed*.9;ball.vy=-Math.sqrt(Math.max(10000,speed*speed-ball.vx*ball.vx));}for(const brick of bricks)if(brick.hits&&BrickBreakerRules.reflectBrick(ball,brick)){brick.hits--;score+=10;break;}if(ball.y-ball.r>canvas.height)ball.dead=true;}balls=balls.filter(ball=>!ball.dead);if(!balls.length)loseLife();if(bricks.every(b=>!b.hits)){score+=250;level++;setupLevel();}}
function loseLife(){lives--;if(lives<=0)return finish();paddle.x=300;balls=[{x:360,y:465,r:8,vx:210+level*12,vy:-250-level*14}];launched=false;document.getElementById('status').textContent=`${lives} lives left · launch when ready`;update();}
function loop(time){if(over)return;const dt=Math.min(.032,(time-last)/1000);last=time;simulate(dt);draw();update();frame=requestAnimationFrame(loop);}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);bricks.forEach(b=>{if(!b.hits)return;ctx.fillStyle=colors[b.row%colors.length];ctx.fillRect(b.x,b.y,b.w,b.h);if(b.hits>1){ctx.strokeStyle='#fff8';ctx.strokeRect(b.x+2,b.y+2,b.w-4,b.h-4);}});ctx.fillStyle='#f7f1e8';ctx.fillRect(paddle.x,paddle.y,paddle.w,paddle.h);balls.forEach(ball=>{ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fillStyle='#e3a34b';ctx.fill();});}
function finish(){over=true;cancelAnimationFrame(frame);timer.stop();Storage.recordResult('brick-breaker','complete');Storage.saveHighScore('brick-breaker',score);update();GameUI.showGameOver({title:'Out of balls',message:`Score ${score} · Reached level ${level}`,onRestart:initialise});}
function position(clientX){const rect=canvas.getBoundingClientRect();paddle.x=Math.max(0,Math.min(canvas.width-paddle.w,(clientX-rect.left)*canvas.width/rect.width-paddle.w/2));}
function update(){const s=Storage.getStats('brick-breaker');document.getElementById('games-played').textContent=s.gamesPlayed;document.getElementById('high-score').textContent=Storage.getHighScore('brick-breaker')??0;document.getElementById('time-played').textContent=`${Math.floor(s.timePlayed/60)}m ${s.timePlayed%60}s`;document.getElementById('score').textContent=score;document.getElementById('lives').textContent=lives;document.getElementById('level').textContent=level;}
function setup(){document.querySelector('.restart-btn').onclick=initialise;canvas.addEventListener('pointermove',e=>position(e.clientX));canvas.addEventListener('pointerdown',e=>{position(e.clientX);launch();});document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')paddle.x=Math.max(0,paddle.x-35);if(e.key==='ArrowRight')paddle.x=Math.min(canvas.width-paddle.w,paddle.x+35);if(e.key===' '){e.preventDefault();launch();}});window.addEventListener('pagehide',()=>{cancelAnimationFrame(frame);timer.stop();});window.addEventListener('pageshow',event=>{if(event.persisted)initialise();});initialise();}window.initGame=window.restartGame=initialise;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup,{once:true});else setup();})();
